ITM_Finals/ITM_Finals/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('catalog.urls')),
    path('products/', include('products.urls')),
    path('quotation/', include('quotation.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ITM_Finals/catalog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name='contact'),
    path('terms/', views.terms, name='terms'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='catalog/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('my_dashboard/', views.my_dashboard, name='my_dashboard'),
]

ITM_Finals/products/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('manage/', views.manage, name='manage'),
    path('new/', views.new, name='new'),
    path('', views.browse, name='browse'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

ITM_Finals/quotation/urls.py
from django.urls import path
from . import views

app_name = 'quotation'

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateItem, name='update_item'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('<int:id>/my_orders_items/',views.my_orders_items, name='my_orders_items'),
    path('process_order/', views.process_order, name='process_order'),
    path('quote_success/', views.quote_success, name='quote_success'),
]

ITM_Finals/catalog/models.py
from django.db import models

# Create your models here.

ITM_Finals/catalog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Enter your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder' : 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'Enter your first name',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'Enter your last name',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Create your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Re-enter your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

ITM_Finals/catalog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout

from .models import *
from products.models import Category, Product
from quotation.models import ShippingAddress

from .forms import SignupForm, LoginForm 


def index(request):
    products = Product.objects.filter(available=True)[0:9]
    
    return render(request, 'catalog/index.html', {
        'products' : products,
    }
)
    
def contact(request):
    return render(request, 'catalog/contact.html')

def terms(request):
    return render(request, 'catalog/terms.html')

def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            return redirect('/login/')
        
    else:
        form = SignupForm()
    
    return render(request, 'catalog/signup.html', {
        'form': form
    })
    
def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        
        if form.is_valid():
            form.save()
            
            return redirect('catalog/index.html', {
                'form' : form
            })
    
    else:
        form = LoginForm()

def logout_view(request):
    logout(request)
    return render(request, 'catalog/logout.html')

def my_dashboard(request):
    return render(request, 'catalog/my_dashboard.html')

ITM_Finals/catalog/templates/catalog/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>
        {% load static %}

        <script type="text/javascript">    
            var user = '{{request.user}}'
    
            function getToken(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length +1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length +1));
                        break;
                    }
                }
            }
            return cookieValue;
            }
        var csrftoken = getToken('csrftoken');
        </script>
        
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

        <title>{% block title %} {% endblock %} | Papers and Pens </title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <div class="flex items-center space-x-6">
                <a href="/" class="text-xl font-semibold mb-4 sm:mb-0 sm:text-2xl flex items-center">
                    <img src="{% static 'images/logo.png' %}" class="w-20 h-16 mr-2">
                    Papers and Pens</a>
                <a href="{% url 'catalog:index' %}" class="text-lg font-semibold hover:text-gray-500">Home</a>
                <a href="{% url 'product:browse' %}" class="text-lg font-semibold hover:text-gray-500">Browse Products</a>
            </div>

            <div class="space-x-2 sm:space-x-6"> 
                {% if request.user.is_superuser %}
                    <a href="{% url 'product:new' %}" class="text-lg font-semibold hover:text-gray-500">Add Product</a>
                    <a href="{% url 'product:manage' %}" class="text-lg font-semibold hover:text-gray-500">Manage Products</a>
                    <a href="{% url 'catalog:logout' %}" class="px-4 py-2 text-lg font-semibold bg-gray-500 text-white hover:bg-gray-700 rounded-xl">Log Out</a>
                {% elif request.user.is_authenticated %}    
                    <div class="flex items-center space-x-4">
                        <a href="{% url 'quotation:cart' %}" class="px-4 py-2 text-lg font-semibold bg-purple-500 text-white hover:bg-gray-700 rounded-xl" id="cart-total">My Form - {{cartItems}}</a>
                        <a href="{% url 'catalog:my_dashboard' %}" class="px-4 py-2 text-lg font-semibold bg-pink-500 text-white hover:bg-gray-700 rounded-xl">My Dashboard</a>
                        <a href="{% url 'catalog:logout' %}" class="px-4 py-2 text-lg font-semibold bg-gray-500 text-white hover:bg-gray-700 rounded-xl">Log Out</a>
                    </div>
                {% else %}
                    <a href="{% url 'catalog:login' %}" class="px-4 py-2 text-lg font-semibold bg-purple-500 text-white hover:bg-gray-700 rounded-xl">Log In</a>
                    <a href="{% url 'catalog:signup' %}" class="px-4 py-2 text-lg font-semibold bg-gray-500 text-white hover:bg-gray-700 rounded-xl">Sign Up</a>
                {% endif %}
            </div>
        </nav>
        

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 sm:flex sm:justify-between bg-gray-800">
            <div class="w-full sm:w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-200">About</h3>
                <p class="text-lg text-gray-500">Papers and Pens is a wholesaling business that sells a variety of office supplies.</p> 
            </div>
        
            <div class="w-full sm:w-1/3">
                <h3 class="mb-5 font-semibold text-gray-200">Menu</h3>
                <ul class="space-y-2">
                    <li><a href="{% url 'catalog:index' %}" class="text-lg text-purple-500">Home</a></li>
                    <li><a href="{% url 'catalog:contact' %}" class="text-lg text-purple-500">Contact</a></li>
                    <li><a href="{% url 'catalog:terms' %}" class="text-lg text-purple-500">Terms of Use</a></li>
                </ul>
            </div>

            <div class="w-full sm:w-1/3">
                <h3 class="mb-5 font-semibold text-gray-200">Shop</h3>
                <ul class="space-y-2">
                    <li><a href="{% url 'product:browse' %}" class="text-lg text-purple-500">Browse Products</a></li>
                </ul>
            </div>

            <div class="w-full sm:w-1/3">
                <h3 class="mb-5 font-semibold text-gray-200">Account</h3>
                <ul class="space-y-2">

                    {% if request.user.is_superuser %}
                        <li><a href="{% url 'product:new' %}" class="text-lg text-purple-500">Add Product</a></li>
                        <li><a href="{% url 'product:manage' %}" class="text-lg text-purple-500">Manage Products</a></li>
                        <li><a href="{% url 'catalog:logout' %}" class="text-lg text-purple-500">Log Out</a></li>
                    {% elif request.user.is_authenticated %}
                        <li><a href="{% url 'quotation:cart' %}" class="text-lg text-purple-500">My Form</a></li>    
                        <li><a href="{% url 'catalog:my_dashboard' %}" class="text-lg text-purple-500">My Dashboard</a></li>
                        <li><a href="{% url 'catalog:logout' %}" class="text-lg text-purple-500">Log Out</a></li>
                    {% else %}
                        <li><a href="{% url 'catalog:signup' %}" class="text-lg text-purple-500">Sign Up</a></li>
                        <li><a href="{% url 'catalog:login' %}" class="text-lg text-purple-500">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </footer>
        
    </body>
</html>

ITM_Finals/catalog/templates/catalog/catalog-sidebar.html
<div class="list-group">
    <a href="{% url 'catalog:my_orders' %}" class="list-group-item">Order History</a>
</div>

ITM_Finals/catalog/templates/catalog/contact.html
{% extends 'catalog/base.html'%}

{% block title %} Contact {% endblock %}

{% block content %}
    <h1>Contact Us!</h1>
    <li>Email: papersandpens@obf.ateneo.edu</li>
    <li>Call us: +63 917 123 4567</li>
{% endblock %}

ITM_Finals/catalog/templates/catalog/index.html
{% extends 'catalog/base.html'%}

{% block title %} Welcome {% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <strong class="mb-12 text-3xl text-center">Welcome back, {{ user.first_name }}!</strong>
    {% else %}
        <strong class="mb-12 text-3xl text-center">Welcome to Papers and Pens!</strong>
    {% endif %}

    <div class="mt-6 px-6 py-12 bg-purple-100 rounded-xl">
        <h2 class="mb-12 text-3xl text-center">Latest Products</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for product in products %}
                <div class="product-container">
                    <a href="{% url 'product:detail' product.id %}">
                        <div class="image-container">
                            <img src="{{ product.image.url }}" class="product-image" alt="{{ product.product_name }}">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ product.product_name }}</h2>
                            <p class="text-gray-500">Php{{ product.price | floatformat:2 }}</p>
                        </div>
                    </a>    

                    <div class="button-container">
                        {% if request.user.is_superuser %}
                            <div class='mt-6 pg-6 bg-gray rounded-xl'>
                                <a href="{% url 'product:edit' product.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-purple-500 text-white rounded-xl">Edit</a>
                                <a href="{% url 'product:delete' product.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
                            </div>    
                        {% else %}
                            <button data-product={{product.id}} data-action="add" class="py-2 px-4 bg-pink-500 text-lg rounded-xl text-white add-btn update-cart">Add to Form</button>
                        {% endif %}

                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div>
        <a href="{% url 'product:browse' %}" style="text-decoration: underline;">
            <h2 class="mb-12 text-3xl text-center">Shop All Products</h2>
        </a>
    </div>

    <style>
        .product-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 20px;
        }
    
        .product-container {
            width: 100%; 
            border: 1px solid white;
            border-color: gray;
            border-radius: 8px;
            background-color: white;
            display: flex;
            flex-direction: column;
        }
    
        .image-container {
            width: 100%;
            height: 200px;
            overflow: hidden; 
        }
    
        .product-image {
            width: 100%;
            height: 100%;
            object-fit: contain;
        }

        .button-container {
            display: flex;
            justify-content: center;
            margin-top: auto;
        }
    
        .p-6 {
            padding: 1rem; 
        }
    </style>
    
{% endblock %}

ITM_Finals/catalog/templates/catalog/login.html
{% extends 'catalog/base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log In</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Enter password</label><br>
            {{ form.password }}
        </div>    

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-purple-500 hover:bg-purple-700 rounded-xl text-white">Submit</button>
        <p class="mt-6">Don't have an account? <a href="{% url 'catalog:signup' %}" class="text-purple-500 hover:text-blue-700">Sign Up</a></p>
</div>
{% endblock %}

ITM_Finals/catalog/templates/catalog/logout.html
{% extends 'catalog/base.html'%}

{% block title %} Welcome {% endblock %}

{% block content %}
<strong class="mb-12 text-3xl text-center">Thank you for visiting Papers and Pens.</strong>
    <div class="mt-6 px-6 py-12 bg-purple-100 rounded-xl">
        <h2 class="mb-12 text-3xl text-center">You've been logged out.</h2> 
        <a href="{% url 'catalog:login' %}" style="text-decoration: underline;">
            <p class="mb-12 text-3xl text-center"> Log in again here.</p>
        </a>
    </div>

    
    
{% endblock %}

ITM_Finals/catalog/templates/catalog/my_dashboard.html
{% extends 'catalog/base.html'%}

{% block title %} Dashboard {% endblock %}

{% block content %}
<main class='container my-4'>
    <h3 class='my-4 border-bottom pb-1'>My Dashboard</h3>
    <div class='row'>
        <div class="col-md-3">
            <a href="{% url 'quotation:my_orders' %}" class="btn btn-success px-4 py-2 text-lg font-semibold bg-purple-500 text-white hover:bg-gray-700 rounded-xl">View Order History</a>
        </div>
        <div class="col-md-9"></div>
    </div>
</main>
{% endblock %}

ITM_Finals/catalog/templates/catalog/signup.html
{% extends 'catalog/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign Up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email Address</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">First Name</label><br>
            {{ form.first_name }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Last Name</label><br>
            {{ form.last_name }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Create password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Re-enter password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-purple-500 hover:bg-purple-700 rounded-xl text-white">Submit</button>
        <p class="mt-6">Already have an account? <a href="{% url 'catalog:login' %}" class="text-purple-500 hover:text-blue-700">Log In</a></p>
</div>
{% endblock %}