ITM_Finals/ITM_Finals/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('catalog.urls')),
    path('products/', include('products.urls')),
    path('quotation/', include('quotation.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ITM_Finals/catalog/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name="index"),
    path('contact/', views.contact, name='contact'),
    path('terms/', views.terms, name='terms'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='catalog/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('my_dashboard/', views.my_dashboard, name='my_dashboard'),
]

ITM_Finals/products/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('manage/', views.manage, name='manage'),
    path('new/', views.new, name='new'),
    path('', views.browse, name='browse'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

ITM_Finals/quotation/urls.py
from django.urls import path
from . import views

app_name = 'quotation'

urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateItem, name='update_item'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('<int:id>/my_orders_items/',views.my_orders_items, name='my_orders_items'),
    path('process_order/', views.process_order, name='process_order'),
    path('quote_success/', views.quote_success, name='quote_success'),
]

ITM_Finals/quotation/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product
    
class Customer(models.Model):
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name
    
class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total 
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total 
    
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total= self.product.price * self.quantity
        return total 

class ShippingAddress(models.Model): 
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(max_length=200, null=True)

    def __str__(self):
        return self.address

    

ITM_Finals/quotation/forms.py
from django import forms

ITM_Finals/quotation/views.py
from django.shortcuts import render, redirect

from django.http import JsonResponse
import json
import datetime
from .models import *
from .forms import *

from pdb import post_mortem

def my_orders(request):
    my_orders=Order.objects.filter(customer = Customer.objects.get(email=request.user.email)).order_by('-id')
    return render(request, 'quotation/my_orders.html',{
        'my_orders':my_orders,
        })

def my_orders_items(request, id):
    order=Order.objects.get(id=id)
    orders_items=OrderItem.objects.filter(order=order).order_by('-id')
    return render(request, 'quotation/my_orders_items.html',{
        'orders_items':orders_items,
        })

def process_order (request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = Customer.objects.get(email=request.user.email)
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        total = float(data['form']['total'])
        order.transaction_id = transaction_id

        if total == order.get_cart_total:
            order.complete = True
        order.save()

        if order.shipping == True:
            ShippingAddress.objects.create(
                customer=customer,
                order=order,
                address=data['shipping']['address'],
                city=data['shipping']['city'],
                state=data['shipping']['state'],
                zipcode=data['shipping']['zipcode'],
            )

    else:
        print('Please log in first before proceeding.') 
    return JsonResponse('Transaction completed.', safe=False)

def cart(request):
    if request.user.is_authenticated:
        customer = Customer.objects.get(email=request.user.email)
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0}
        cartItems = order['get_cart_items']

    products = Product.objects.all()
    return render(request, 'quotation/cart.html', {
        'items': items,
        'order': order,
        'products':products,
        'cartItems' :cartItems,
    })

def checkout(request):
    if request.user.is_authenticated:
        customer = Customer.objects.get(email=request.user.email)
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0}
        cartItems = order['get_cart_items']

    return render(request, 'quotation/checkout.html', {
        'items' : items, 
        'order' : order,
        'cartItems' :cartItems
    }) 

def updateItem(request):
    data = json.loads(request.body) 
    productId = data['productId']   
    action = data['action']

    print('Action:', action)
    print('productId:', productId)

    customer = customer = Customer.objects.get(email=request.user.email)
    print('Customer:', customer)

    product = Product.objects.get(id=productId) 
    print('Product:', product)

    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    print('Order:', order, 'Created:', created)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product) 
    print('OrderItem:', orderItem, 'Created:', created)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)
    
    orderItem.save()
    print('OrderItem quantity:', orderItem.quantity)

    if orderItem.quantity <= 0:
        orderItem.delete()
        print('OrderItem deleted')

    return JsonResponse('Item was added', safe=False)

def quote_success(request):
    return render(request, 'quotation/quote_success.html')

ITM_Finals/quotation/templates/quotation/cart.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}

<div class="mt-6 px-6 py-12 bg-purple-100 rounded-xl">
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <a class="btn btn-outline-dark font-semibold text-lg" href="{%url 'product:browse' %}">&#x2190; Continue Shopping</a>
                <h2 class="text-center text-3xl font-semibold">Quotation Form</h2>

                {% for item in items %}
                <div class="cart-item">
                    <div class="item-image">
                        <img src="{{ item.product.image.url }}">
                    </div>
                    <div class="item-details">
                        <h5 class="item-title">{{ item.product.product_name }}</h5>
                        
                    </div>
                    <div class="item-total">
                        <p><strong>Price:</strong> Php{{item.get_total | floatformat:2}}</p>
                    </div>
                    <div class="item-actions">
                        <button data-product={{item.id}} data-action="remove" class="chg-quantity update-cart"> - </button>
                        <p class="item-quantity"><strong>Quantity: </strong> {{item.quantity}}</p>
                        <button data-product={{item.id}} data-action="add" class="chg-quantity update-cart"> + </button>
                    </div>
                </div>
                {% endfor %}

                <div class="summary-section">
                    <h4 class="summary-title">Total Number of Items: <strong>{{order.get_cart_items}}</strong></h4>
                    <h4 class="summary-title">Total: <strong>Php {{order.get_cart_total}}</strong></h4>
                </div>

                <a style="float:right; margin:5px" class="btn btn-success px-4 py-2 text-lg font-semibold bg-purple-500 text-white hover:bg-gray-700 rounded-xl" href="{% url 'quotation:checkout' %}">Checkout</a>
            </div>
        </div>
    </div>
</div>

<style>
    .summary-section {
        margin-bottom: 20px;
        border-bottom: 1px solid;
        padding-bottom: 10px;
    }
    
    .summary-title {
        margin-bottom: 10px;
    }
    
    .cart-item {
        display: flex;
        margin-bottom: 20px;
    }
    
    .item-image {
        flex: 1;
    }
    
    .item-details {
        flex: 2;
        padding: 10px;
    }
    
    .item-total {
        flex: 1;
    }
    
    .item-actions {
        flex: 1;
    }
</style>

{% endblock %}


    

ITM_Finals/quotation/templates/quotation/checkout.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}

<div class="mt-6 px-6 py-12 bg-purple-100 rounded-xl">
<div class="row">
    <div class="col-lg-6">
        <a class="btn btn-outline-dark font-semibold text-lg" href="{% url 'quotation:cart' %}">&#x2190; Back to Quotation Form</a>
        <div class="box-element" id="form-wrapper">
            <form id="form">
                <div id="user-info">
                    <div class="form-field">
                        <input required class="form-control" type="text" name="name" placeholder="Name..">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="email" name="email" placeholder="Email..">
                    </div>
                </div>

                <div id="shipping-info">
                    <hr>
                    <p>Shipping Information:</p>
                    <hr>
                    <div class="form-field">
                        <input class="form-control" type="text" name="address" placeholder="Address..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="city" placeholder="City..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="state" placeholder="State..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="zipcode" placeholder="Zip Code..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="country" placeholder="Country..">
                    </div>
                </div>

                <hr>
                <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
            </form>
        </div>
        <br>

        <div class="box-element hidden" id="payment-info">
            <small>Paypal Options</small>
        </div>

    </div>

    <div class="col-lg-6">
        <div class="box-element">
            <hr>
            <h3>Order Summary</h3>
            <hr>
            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{item.product.image.url}}"></div>
                <div style="flex:2"><p>{{item.product.product_name}}</p></div>
                <div style="flex:1"><p>Php{{item.product.price | floatformat:2}}</p></div>
                <div style="flex:1"><p>Quantity: {{item.quantity}}</p></div>
            </div>
            {% endfor %}
            <a style="float:right; margin:5px" class="btn btn-success px-4 py-2 text-lg font-semibold bg-purple-500 text-white hover:bg-gray-700 rounded-xl" href="{% url 'quotation:quote_success' %}">Submit Form</a>

            <h5>Total Number of Items: {{order.get_cart_items}}</h5>
            <h5>Total: Php{{order.get_cart_total|floatformat:2}}</h5>
        </div>
    </div>
</div>
</div>

<script type="text/javascript">

    var form = document.getElementById('form')

    form.addEventListener('submit', function(e){
        e.preventDefault()
        console.Log('Form submitted...')
        document.getElementById('form-button').classlist.add('hidden')
        document.getElementById('payment-info').classlist.remove('hidden')

    })

    function submitFormData(){
        console.Log('Submit button was clicked')

        var userFormData = {
            'name':null,
            'email':null,
            'total':total, 
        }

        var shippingInfo = {
            'address':null,
            'city':null,
            'state':null,
            'zipcode':null,
        }

        if(shipping != 'False'){
            shippingInfo.address = form.address.value
            shippingInfo.city = form.city.value
            shippingInfo.state = form.state.value
            shippingInfo.zipcode = form.zipcode.value
        }

        if(user == 'AnonymousUser'){
            userFormData.name = form.name.value
            userFormData.email = form.email.value
            
        }
        var url ="/process_order/"
        fetch(url,{
            method:'POST',
            headers:{
                'Content-Type':'application/json',
                'X-CSRFToken':csrftoken,
            },
            body:JSON.stringify({'form':userFormData, 'shipping':shippingInfo}),
        })
        .then((response) => response.json())
        .then((data) => {
            console.Log('Success', data);
            alert('Transaction completed');
            window.location.href = "{% url 'quotation:quote_success' %}"
            })
        
        var url = '/process_order/'
        fetch(url,{
            method:'POST',
            headers:{
                'Content-Type':'application/json',
                'X-CSRFToken':csrftoken,
            }
            body:JSON.stringify({'form':userFormData, 'shipping':shippingInfo})
        })
        .then((response) => response.json())
        .then((data) => {
            console.log('Success:' data);
            alert('Transaction completed');
            window.location.href = "{% url 'quotation:quote_success' %}"
        })
    }
</script> 
{% endblock content %}

ITM_Finals/quotation/templates/quotation/my_orders.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}

<div class="mt-6 px-6 py-12 bg-purple-100 rounded-xl">
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <h2 class="text-center text-3xl semibold">Order History</h2>

                <hr>
                <h3>Order History</h3>
                <hr>
                {% for order in my_orders %}
                <div class="cart-row">
                    <div style="flex:2"><a class="btn btn-success px-4 py-2 font-semibold bg-purple-500 text-white hover:bg-gray-700 rounded-xl" href="{% url 'quotation:my_orders_items' order.id %}" class="btn btn-sm btn-dark">Order ID: {{order.id}}</a></div>
                    <div style="flex:2"><p>Product: {{order.product.product_name}}</p></div>
                    <div style="flex:1"><p>Php{{order.product.price}}</p></div>
                    <div style="flex:1"><p>Quantity: {{order.quantity}}</p></div>
                    <div style="flex:1"><p>Date Ordered: {{order.date_ordered}}</p></div>
                </div>
                {% endfor %}

                <h5>Items: {{order.get_cart_items}}</h5>
                <h5>Total: Php{{order.get_cart_total|floatformat:2}}</h5>

                <a style="float:right; margin:5px" class="btn btn-success px-4 py-2 text-lg font-semibold bg-purple-500 text-white hover:bg-gray-700 rounded-xl" href="{% url 'catalog:index' %}">Back to Home Page</a>
            </div>
        </div>
    </div>
</div>

<style>
    .summary-section {
        margin-bottom: 20px;
        border-bottom: 1px solid;
        padding-bottom: 10px;
    }
    
    .summary-title {
        margin-bottom: 10px;
    }
    
    .cart-item {
        display: flex;
        margin-bottom: 20px;
    }
    
    .item-image {
        flex: 1;
    }
    
    .item-details {
        flex: 2;
        padding: 10px;
    }
    
    .item-total {
        flex: 1;
    }
    
    .item-actions {
        flex: 1;
    }
</style>

{% endblock %}


    

ITM_Finals/quotation/templates/quotation/my_orders_items.html
{% extends 'catalog/base.html' %}
{% load static %}
{% block content %}

<div class="mt-6 px-6 py-12 bg-purple-100 rounded-xl">
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <h2 class="text-center text-3xl semibold">Order {{order.id}} Details</h2>

                <hr>
                <h3>Order Summary</h3>
                <hr>
                {% for order in my_orders %}
                <div class="cart-row">
                    <div style="flex:2"><img class="row-image" src="{{order.product.image.url}}"></div>
                    <div style="flex:2"><p>Product: {{order.product.product_name}}</p></div>
                    <div style="flex:1"><p>Php{{order.product.price}}</p></div>
                    <div style="flex:1"><p>Quantity: {{order.quantity}}</p></div>
                </div>
                {% endfor %}

                <h5>Items: {{order.get_cart_items}}</h5>
                <h5>Total: Php{{order.get_cart_total|floatformat:2}}</h5>

                <a style="float:right; margin:5px" class="btn btn-success px-4 py-2 text-lg font-semibold bg-purple-500 text-white hover:bg-gray-700 rounded-xl" href="{% url 'catalog:index' %}">Back to Home Page</a>
            </div>
        </div>
    </div>
</div>

<style>
    .summary-section {
        margin-bottom: 20px;
        border-bottom: 1px solid;
        padding-bottom: 10px;
    }
    
    .summary-title {
        margin-bottom: 10px;
    }
    
    .cart-item {
        display: flex;
        margin-bottom: 20px;
    }
    
    .item-image {
        flex: 1;
    }
    
    .item-details {
        flex: 2;
        padding: 10px;
    }
    
    .item-total {
        flex: 1;
    }
    
    .item-actions {
        flex: 1;
    }
</style>

{% endblock %}


    

ITM_Finals/quotation/templates/quotation/quote.html
<!doctype html>

<html>
    <head>
        <title>Quotation Form</title>
    </head>
    <body>
        <h1>Request a Quotation</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </body>
</html>

ITM_Finals/quotation/templates/quotation/quote_success.html
<!doctype html>

<html>
<head>
    <title>Quotation Form Success!</title>
</head>
<body>
    <h1>Quotation Successfully Sent</h1>
    <p> Thank you for submitting your quotation request. We will get back to you soon.</p>
</body>
</html>